# Generated by Django 6.0.4 on 2026-08-09 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('PHONE_CALL', 'Phone call'), ('SMS', 'SMS'), ('VISIT', 'Visit'), ('REMINDER', 'Reminder'), ('PROMISE_TO_PAY', 'Promise to pay'), ('ESCALATION', 'Escalation')], max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('promised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to='customers.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_actions', to='loans.loan')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
