# Generated by Django 6.0.4 on 2026-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(db_index=True, max_length=10)),
                ('branch_code', models.CharField(blank=True, default='', max_length=12)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Number sequences',
                'unique_together': {('prefix', 'branch_code', 'year')},
            },
        ),
    ]
