# Generated by Django 6.0.4 on 2026-08-09 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('weight', models.IntegerField(default=10, help_text='Percentage weight 0-100')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_income', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('verified_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('existing_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('disposable_income', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit_score', models.IntegerField(default=0)),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=12)),
                ('recommendation', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CONDITIONAL', 'Conditional approval')], default='APPROVE', max_length=12)),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('recommended_term_months', models.IntegerField(blank=True, null=True)),
                ('collateral_assessed', models.BooleanField(default=False)),
                ('capacity_notes', models.TextField(blank=True)),
                ('character_notes', models.TextField(blank=True)),
                ('collateral_notes', models.TextField(blank=True)),
                ('conditions_notes', models.TextField(blank=True)),
                ('overall_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessment', to='loans.loanapplication')),
                ('credit_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
