# Generated by Django 6.0.4 on 2026-08-09 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('PERMISSION_CHANGED', 'Permission changed'), ('CUSTOMER_CREATED', 'Customer created'), ('CUSTOMER_UPDATED', 'Customer updated'), ('CUSTOMER_DOCUMENT_VERIFIED', 'Customer document verified'), ('GROUP_CREATED', 'Group created'), ('LOAN_APPLICATION_CREATED', 'Loan application created'), ('LOAN_APPLICATION_SUBMITTED', 'Loan application submitted'), ('LOAN_APPLICATION_UPDATED', 'Loan application updated'), ('CREDIT_ASSESSED', 'Credit assessment performed'), ('LOAN_RECOMMENDED', 'Loan recommended'), ('LOAN_APPROVED', 'Loan approved'), ('LOAN_REJECTED', 'Loan rejected'), ('LOAN_DISBURSED', 'Loan disbursed'), ('LOAN_RESTRUCTURED', 'Loan restructured'), ('LOAN_WRITTEN_OFF', 'Loan written off'), ('REPAYMENT_CREATED', 'Repayment created'), ('REPAYMENT_REVERSED', 'Repayment reversed'), ('SAVINGS_DEPOSIT', 'Savings deposit'), ('SAVINGS_WITHDRAWAL', 'Savings withdrawal'), ('TELLER_OPENED', 'Teller session opened'), ('TELLER_CLOSED', 'Teller session closed'), ('CASH_ADJUSTED', 'Cash adjusted'), ('JOURNAL_CREATED', 'Journal entry created'), ('JOURNAL_APPROVED', 'Journal entry approved'), ('JOURNAL_POSTED', 'Journal entry posted'), ('EXPENSE_CREATED', 'Expense created'), ('SETTING_CHANGED', 'System setting changed'), ('DATA_EXPORTED', 'Data exported'), ('SYSTEM_EVENT', 'System event')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Request/reference ID', max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organization.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
