# Generated by Django 6.0.4 on 2026-08-09 14:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Branch Manager', 'Branch Manager'), ('Head of Operations', 'Head of Operations'), ('General Manager', 'General Manager')], max_length=60, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('99999999999.00'), max_digits=18)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = more senior')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Approval configurations',
                'ordering': ['priority'],
            },
        ),
    ]
